web/router.ex
defmodule Dogfamily.Router do
  use Dogfamily.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: Dogfamily.Token
    plug Guardian.Plug.LoadResource
  end

  pipeline :back_office_layout do
    plug :put_layout, { Dogfamily.LayoutView, :back_office }
  end

  scope "/back_office", Dogfamily do
    pipe_through [:browser, :back_office_layout, :browser_auth]

    get "/", BackOfficeController, :index

    resources "/users", UserController
    resources "/roles", RoleController
    resources "/brands", BrandController
    resources "/dogs", DogController
    resources "/residences", ResidenceController
  end

  scope "/", Dogfamily do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/", DogRequestController
    post "/new", DogRequestController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", Dogfamily do
  #   pipe_through :api
  # end
end

web/models/residence.ex
defmodule Dogfamily.Residence do
  use Dogfamily.Web, :model

  schema "residences" do
    field :name, :string

    has_many :dogs, Dogfamily.Dog
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end

web/controllers/back_office/residence_controller.ex
defmodule Dogfamily.ResidenceController do
  use Dogfamily.Web, :controller

  alias Dogfamily.Residence
  alias Dogfamily.Dog

  plug :put_layout, "back_office.html"

  def index(conn, _params) do
    residences = Repo.all(Residence)
    render(conn, "index.html", residences: residences)
  end

  def new(conn, _params) do
    changeset = Residence.changeset(%Residence{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"residence" => residence_params}) do
    changeset = Residence.changeset(%Residence{}, residence_params)

    case Repo.insert(changeset) do
      {:ok, _residence} ->
        conn
        |> put_flash(:info, "Residence created successfully.")
        |> redirect(to: residence_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)
    dogs = Repo.all(Dog, residence_id: id)
    render(conn, "show.html", residence: residence, dogs: dogs)
  end

  def edit(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)
    changeset = Residence.changeset(residence)
    render(conn, "edit.html", residence: residence, changeset: changeset)
  end

  def update(conn, %{"id" => id, "residence" => residence_params}) do
    residence = Repo.get!(Residence, id)
    changeset = Residence.changeset(residence, residence_params)

    case Repo.update(changeset) do
      {:ok, residence} ->
        conn
        |> put_flash(:info, "Residence updated successfully.")
        |> redirect(to: residence_path(conn, :show, residence))
      {:error, changeset} ->
        render(conn, "edit.html", residence: residence, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(residence)

    conn
    |> put_flash(:info, "Residence deleted successfully.")
    |> redirect(to: residence_path(conn, :index))
  end
end

web/controllers/residence_controller.ex
defmodule Dogfamily.ResidenceController do
  use Dogfamily.Web, :controller

  alias Dogfamily.Residence
  alias Dogfamily.Dog

  def index(conn, _params) do
    residences = Repo.all(Residence)
    render(conn, "index.html", residences: residences)
  end

  def new(conn, _params) do
    changeset = Residence.changeset(%Residence{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"residence" => residence_params}) do
    changeset = Residence.changeset(%Residence{}, residence_params)

    case Repo.insert(changeset) do
      {:ok, _residence} ->
        conn
        |> put_flash(:info, "Residence created successfully.")
        |> redirect(to: residence_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)
    dogs = Repo.all(Dog, residence_id: id)
    render(conn, "show.html", residence: residence, dogs: dogs)
  end

  def edit(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)
    changeset = Residence.changeset(residence)
    render(conn, "edit.html", residence: residence, changeset: changeset)
  end

  def update(conn, %{"id" => id, "residence" => residence_params}) do
    residence = Repo.get!(Residence, id)
    changeset = Residence.changeset(residence, residence_params)

    case Repo.update(changeset) do
      {:ok, residence} ->
        conn
        |> put_flash(:info, "Residence updated successfully.")
        |> redirect(to: residence_path(conn, :show, residence))
      {:error, changeset} ->
        render(conn, "edit.html", residence: residence, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    residence = Repo.get!(Residence, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(residence)

    conn
    |> put_flash(:info, "Residence deleted successfully.")
    |> redirect(to: residence_path(conn, :index))
  end
end

web/views/residence_view.ex
defmodule Dogfamily.ResidenceView do
  use Dogfamily.Web, :view
end

web/templates/residence/edit.html.eex
<h2>Edit residence</h2>

<%= render "form.html", changeset: @changeset,
                        action: residence_path(@conn, :update, @residence) %>

<%= link "Back", to: residence_path(@conn, :index), class: "btn btn-default" %>

web/templates/residence/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/residence/index.html.eex
<h2>Listing residences</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for residence <- @residences do %>
    <tr>
      <td><%= residence.name %></td>

      <td class="text-right">
        <%= link "Show", to: residence_path(@conn, :show, residence), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: residence_path(@conn, :edit, residence), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: residence_path(@conn, :delete, residence), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New residence", to: residence_path(@conn, :new), class: "btn btn-default" %>

web/templates/residence/new.html.eex
<h2>New residence</h2>

<%= render "form.html", changeset: @changeset,
                        action: residence_path(@conn, :create) %>

<%= link "Back", to: residence_path(@conn, :index), class: "btn btn-default" %>

web/templates/residence/show.html.eex
<h2>Show residence</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @residence.name %>
  </li>

</ul>


<h3>Dog List</h3>
<%= for dog <- @dogs do %>
  <ul>
      <li><b>Name:</b> <%= dog.name %></li>
      <li><b>Age:</b> <%= dog.age %></li>
      <li><b>Photo:</b> <%= !is_nil(dog.photo) %></li>
  </ul>
<% end %>

<%= link "New Dog", to: dog_path(@conn, :new, @residence), class: "btn btn-default" %>
<%= link "Edit", to: residence_path(@conn, :edit, @residence), class: "btn btn-default" %>
<%= link "Back", to: residence_path(@conn, :index), class: "btn btn-default" %>